application:
  security:
    jwt:
      secret-key: E43D67215CC2EFF7B83BDE643CF9FE43D67215CC2EFF7B83BDE643CF9F
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    org.springframework.security.web: DEBUG